apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mareackr.azurecr.io/webscrapping_nginx:v1.24
        ports:
        - containerPort: 443
          protocol: TCP
