version: "3.7"
services:
  webscrapping:
    container_name: webscrapping
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.webscrapping
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - webscrapnet
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - webscrapnet
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - webscrapnet
networks:
  webscrapnet:
