apiVersion: apps/v1
kind: Deployment
metadata:
  name: webscrapping
spec:
  selector:
    matchLabels:
      app: webscrapping
  replicas: 1
  template:
    metadata:
      labels:
        app: webscrapping
    spec:
      containers:
      - name: webscrapping
        image: ENV_AZURE_SERVER_REG/webscrapping_webscrapping:ENV_TAG
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: SECRET_KEY
          value: "wordpress"
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wordpress"
        - name: MYSQL_PASSWORD
          value: "wordpress"
