apiVersion: apps/v1
kind: Deployment
metadata:
  name: webscrapping
spec:
  selector:
    matchLabels:
      app: webscrapping
  replicas: 1
  template:
    metadata:
      labels:
        app: webscrapping
    spec:
      containers:
      - name: webscrapping
        image: ${AZURE_SERVER_REG}/webscrapping_webscrapping:${TAG}
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: SECRET_KEY
          value: ${SECRET_KEY}
        - name: MYSQL_DATABASE
          value: ${MYSQL_DATABASE}
        - name: MYSQL_USER
          value: ${MYSQL_USER}
        - name: MYSQL_PASSWORD
          value: ${MYSQL_PASSWORD}
