FROM nginx

RUN apt update -qq && apt install -qq openssl

RUN mkdir /cert \
	&& cd /cert \
	&&  openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365 -subj "/C=FR/ST=Paris/L=Paris/O=Global Security/OU=IT Department/CN=${HOSTNAME}"
