kind: Service
apiVersion: v1
metadata:
  name: nginx
  name: azure-load-balancer
spec:
  selector:
    app: nginx
  ports:
    - port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 13.92.179.241
