---
apiVersion: v1
kind: Pod
metadata:
  name: webscrapping
  labels:
    app: webscrapping
spec:
  containers:
  - name: webscrapping
    image: mareackr.azurecr.io/webscrapping_webscrapping:v1.24
    imagePullPolicy: Always
    ports:
    - containerPort: 5000
    env:
    - name: SECRET_KEY
      value: "SECRET"
    - name: MYSQL_DATABASE
      value: "wordpress"
    - name: MYSQL_USER
      value: "wordpress"
    - name: MYSQL_PASSWORD
      value: "wordpress"

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: mareackr.azurecr.io/webscrapping_nginx:v1.24
    imagePullPolicy: Always
    ports:
    - containerPort: 443

---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - name: mariab
    image: mariadb
    imagePullPolicy: Always
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "wordpress"
    - name: MYSQL_USER
      value: "wordpress"
    - name: MYSQL_PASSWORD
      value: "wordpress"
    - name: MYSQL_DATABASE
      value: "wordpress"
